### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by just-maxime** [persistz/derivative-free-attack#1]
Hello, I want to run your code, but I found that 'utils' are missing. Could you provide?

**Comment by persistz** [comment]
Thanks, I will check this issue and fix it.

**Comment by persistz** [comment]
Hi @just-maxime ,

I've uploaded missing files and fixed some other potential issues.

In addition, since the original experiment was carried out in 2019 and our school's server has been upgraded many times, I cannot accurately provide the version of the third-party library used in the original experiment, but in a new env (scipy= 1.0.0, keras=2.1.6), the code can run normally. If you encounter some problems related to third-party libraries, you can refer to these versions or use another alternative func. 

Thank you for your interest in our work. Please check it.
